name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.4.2/symcrypt-windows-amd64-release-103.4.2-171f697.zip"
            run-tests: true
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.4.2/symcrypt-windows-arm64-release-103.4.2-171f697.zip"
            run-tests: false # Windows doesn't support ARM64 emulation
          - target: x86_64-unknown-linux-gnu
            symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.4.2/symcrypt-linux-generic-amd64-release-103.4.2-171f697.tar.gz"
            os: ubuntu-latest
            run-tests: true
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            symcrypt: "https://github.com/microsoft/SymCrypt/releases/download/v103.4.2/symcrypt-linux-generic-arm64-release-103.4.2-171f697.tar.gz"
            run-tests: false
            
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}    
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Install host target
      run: rustup target add ${{ matrix.target }}

    - name: Download SymCrypt
      shell: pwsh
      run: |
        $dir = $(Get-Item .).FullName
        if ("${{ matrix.symcrypt }}" -match "\.tar\.gz$") {
          Invoke-WebRequest -Uri ${{ matrix.symcrypt }} -OutFile symcrypt.tar.gz
          New-Item -ItemType Directory -Force -Path symcrypt
          tar -xzf symcrypt.tar.gz -C symcrypt
          echo "$dir/symcrypt/lib" >> $env:GITHUB_PATH
          echo "LD_LIBRARY_PATH=$dir/symcrypt/lib:$env:LD_LIBRARY_PATH" >> $env:GITHUB_ENV
          echo "LIBRARY_PATH=$dir/symcrypt/lib:$env:LIBRARY_PATH" >> $env:GITHUB_ENV
          echo "SYMCRYPT_LIB_PATH=$dir/symcrypt/lib" >> $env:GITHUB_ENV
        } else {
          Invoke-WebRequest -Uri ${{ matrix.symcrypt }} -OutFile symcrypt.zip
          New-Item -ItemType Directory -Force -Path symcrypt
          Expand-Archive -Path symcrypt.zip -DestinationPath symcrypt
          echo "$dir/symcrypt/dll" >> $env:GITHUB_PATH
          echo "SYMCRYPT_LIB_PATH=$dir/symcrypt/dll" >> $env:GITHUB_ENV   
        }

    - name: Build
      run: cargo build --verbose --target ${{ matrix.target }}

    - name: Run tests
      if: matrix.run-tests
      shell: pwsh
      run: |
        Write-Output "SYMCRYPT_LIB_PATH=$env:SYMCRYPT_LIB_PATH"
        Write-Output "PATH=$env:PATH"
        cargo test --verbose --target ${{ matrix.target }}
